version: '3'
services:
  app:
    container_name: spring-boot-app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb # Use the service name as the host
      SPRING_DATA_MONGODB_PORT: 27017

  mangodb:
    image: mongo
    ports:
      - 2701:2701
    environment:
      - MONGO_INITDB_USERNAME=root
      - MONGO_INITDB_PASSWORD=root
  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      -REDIS_PASSWORD: root

